version: "3.9" # optional since v1.27.0
services:
  web_api:
    image: web_api
    container_name: web_api_application
    ports:
      - "8000:8000"
  # sql:
  #   image: "mcr.microsoft.com/mssql/server:2019-latest"
  #   container_name: sql_server2022
  #   ports:
  #     # not actually needed, because the two services are on the same network
  #     - "1433:1433"
  #   environment:
  #     - ACCEPT_EULA=y
  #     - SA_PASSWORD=A&VeryComplex123Password
  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      - "7005:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres